# Generated by Django 5.1.1 on 2024-09-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substream', '0002_alter_video_subtitle_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(max_length=255, upload_to='videos/'),
        ),
    ]
