# Generated by Django 5.1.1 on 2024-09-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substream', '0004_alter_video_subtitle_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
    ]
