# Generated by Django 5.1.1 on 2024-09-11 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substream', '0005_alter_video_subtitle_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='subtitle_file',
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle_file', models.FileField(max_length=255, upload_to='subtitles/')),
                ('language', models.CharField(default='Unknown', max_length=50)),
                ('stream_index', models.CharField(max_length=100)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='substream.video')),
            ],
        ),
    ]
