# Generated by Django 5.1.1 on 2024-09-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substream', '0006_remove_video_subtitle_file_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='subtitle_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='timestamp',
            field=models.FloatField(default=0.0),
        ),
    ]
