# Generated by Django 5.1.1 on 2024-09-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substream', '0007_subtitle_subtitle_text_subtitle_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='timestamp',
            field=models.CharField(max_length=12),
        ),
    ]
