# Generated by Django 5.1.1 on 2024-09-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substream', '0008_alter_subtitle_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='subtitle_text',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='timestamp',
        ),
    ]
